/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ihm;

import java.awt.Dimension;
import java.util.Date;
import java.util.HashMap;
import java.util.List;

/**
 * Vue secondaire de l'IHM, permet la visualisation des chambres existantes et
 * leur gestion (création, suppression et modification des chambres) après
 * identification
 *
 * @author riviere
 */
public class GestionDesChambres extends javax.swing.JPanel implements HotelListener {

    private final Controleur controleur;
    private List<Integer> tailles;

    public GestionDesChambres(Controleur controleur) {
        this.controleur = controleur;
        initComponents();
        errorLabel.setVisible(false);
    }

    /**
     * Permet d'affiche le message d'erreur en paramètre dans la zone appropriée
     *
     * @param message d'erreur à afficher
     */
    public void afficherErreur(String message) {
        errorLabel.setText(message);
        errorLabel.setVisible(true);
    }

    /**
     * Rend la zone d'affichage des messages d'erreur invisible
     */
    public void cacherErreur() {
        errorLabel.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listeChambres = new javax.swing.JList();
        jLabel1 = new javax.swing.JLabel();
        supprimerB = new javax.swing.JButton();
        creerB = new javax.swing.JButton();
        modifierB = new javax.swing.JButton();
        numeroF = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        tailleF = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        numeroSF = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        errorLabel = new javax.swing.JLabel();

        setPreferredSize(new Dimension(625,412));
        setLayout(null);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("Gestion des chambres");
        add(jLabel2);
        jLabel2.setBounds(131, 11, 260, 22);

        listeChambres.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        listeChambres.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        listeChambres.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                listeChambresValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(listeChambres);

        add(jScrollPane1);
        jScrollPane1.setBounds(450, 60, 140, 310);

        jLabel1.setText("Chambres existantes");
        add(jLabel1);
        jLabel1.setBounds(460, 40, 140, 14);

        supprimerB.setText("Supprimer");
        supprimerB.setEnabled(false);
        supprimerB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                supprimerBActionPerformed(evt);
            }
        });
        add(supprimerB);
        supprimerB.setBounds(275, 77, 110, 23);

        creerB.setText("Créer");
        creerB.setEnabled(false);
        creerB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                creerBActionPerformed(evt);
            }
        });
        add(creerB);
        creerB.setBounds(270, 200, 81, 23);

        modifierB.setText("Modifier");
        modifierB.setEnabled(false);
        modifierB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modifierBActionPerformed(evt);
            }
        });
        add(modifierB);
        modifierB.setBounds(270, 250, 81, 23);

        org.jdesktop.beansbinding.Binding binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ, listeChambres, org.jdesktop.beansbinding.ELProperty.create("${selectedElement}"), numeroF, org.jdesktop.beansbinding.BeanProperty.create("text_ON_FOCUS_LOST"));
        bindingGroup.addBinding(binding);

        numeroF.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                numeroFCaretUpdate(evt);
            }
        });
        numeroF.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                numeroFKeyReleased(evt);
            }
        });
        add(numeroF);
        numeroF.setBounds(20, 230, 60, 20);

        jLabel3.setText("Numéro");
        add(jLabel3);
        jLabel3.setBounds(20, 210, 50, 14);

        tailleF.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                tailleFCaretUpdate(evt);
            }
        });
        add(tailleF);
        tailleF.setBounds(100, 230, 47, 20);

        jLabel4.setText("Taille");
        jLabel4.setToolTipText("");
        add(jLabel4);
        jLabel4.setBounds(108, 210, 50, 14);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        add(jComboBox1);
        jComboBox1.setBounds(170, 230, 90, 20);

        jLabel5.setText("Catégorie");
        add(jLabel5);
        jLabel5.setBounds(180, 210, 70, 14);

        jLabel6.setText("Numéro");
        add(jLabel6);
        jLabel6.setBounds(126, 80, 60, 14);

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ, listeChambres, org.jdesktop.beansbinding.ELProperty.create("${selectedElement}"), numeroSF, org.jdesktop.beansbinding.BeanProperty.create("text_ON_FOCUS_LOST"));
        bindingGroup.addBinding(binding);

        numeroSF.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                numeroSFCaretUpdate(evt);
            }
        });
        add(numeroSF);
        numeroSF.setBounds(190, 80, 60, 20);

        jButton4.setText("Retour >");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        add(jButton4);
        jButton4.setBounds(470, 380, 110, 23);

        errorLabel.setForeground(new java.awt.Color(255, 51, 51));
        errorLabel.setText("errorLabel");
        add(errorLabel);
        errorLabel.setBounds(0, 320, 220, 90);

        bindingGroup.bind();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        controleur.retourVueP();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void numeroSFCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_numeroSFCaretUpdate
        if (numeroSF.getText().isEmpty()) {
            supprimerB.setEnabled(false);
        } else {
            supprimerB.setEnabled(true);
        }
    }//GEN-LAST:event_numeroSFCaretUpdate

    private void supprimerBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_supprimerBActionPerformed
        controleur.supprimerChambre(numeroSF.getText());
    }//GEN-LAST:event_supprimerBActionPerformed

    private void creerBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_creerBActionPerformed
        controleur.creerChambre(numeroF.getText(), tailleF.getText());
    }//GEN-LAST:event_creerBActionPerformed

    private void tailleFCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_tailleFCaretUpdate
        if ((!tailleF.getText().isEmpty()) && (!numeroF.getText().isEmpty())) {
            modifierB.setEnabled(true);
        } else {
            modifierB.setEnabled(false);
        }
    }//GEN-LAST:event_tailleFCaretUpdate

    private void numeroFKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_numeroFKeyReleased
        if ((!tailleF.getText().isEmpty()) && (!numeroF.getText().isEmpty())) {
            modifierB.setEnabled(true);
            creerB.setEnabled(true);
        } else {
            modifierB.setEnabled(false);
            creerB.setEnabled(false);
        }
    }//GEN-LAST:event_numeroFKeyReleased

    private void numeroFCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_numeroFCaretUpdate
        if ((!tailleF.getText().isEmpty()) && (!numeroF.getText().isEmpty())) {
            modifierB.setEnabled(true);
        } else {
            modifierB.setEnabled(false);
        }
    }//GEN-LAST:event_numeroFCaretUpdate

    private void modifierBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modifierBActionPerformed
        controleur.modifierChambre(numeroF.getText(), tailleF.getText());
    }//GEN-LAST:event_modifierBActionPerformed

    private void listeChambresValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_listeChambresValueChanged
        int index = listeChambres.getSelectedIndex();
        if (index >= 0) {
            tailleF.setText(tailles.get(index) + "");
        } else {
            tailleF.setText("");
        }
    }//GEN-LAST:event_listeChambresValueChanged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton creerB;
    private javax.swing.JLabel errorLabel;
    private javax.swing.JButton jButton4;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList listeChambres;
    private javax.swing.JButton modifierB;
    private javax.swing.JTextField numeroF;
    private javax.swing.JTextField numeroSF;
    private javax.swing.JButton supprimerB;
    private javax.swing.JTextField tailleF;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables

    @Override
    public void init(List<Integer> idsChambre, List<Integer> tailles, HashMap<Integer, List<Integer>> resa, List<Date> datesDebut, List<Integer> nbsJours, List<Integer> idsClient) {
        this.tailles = tailles;
        listeChambres.removeAll();
        listeChambres.setListData(idsChambre.toArray());
    }

    @Override
    public void reservationsModifiees(HashMap<Integer, List<Integer>> resa, List<Date> datesDebut, List<Integer> nbsJours, List<Integer> idsClient) {
    }

    @Override
    public void chambresModifiees(List<Integer> idsChambre, List<Integer> tailles) {
        this.tailles = tailles;
        listeChambres.removeAll();
        listeChambres.setListData(idsChambre.toArray());
        errorLabel.setVisible(false);
    }

    @Override
    public void clientRecherche(String nom, String prenom, String date, int id) {
    }
}
